name: CI

on:
  push:
    branches:
      - main
    pull_request:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci --ignore-scripts
      - run: npm run build --if-present
      - run: npm test
